name: draw python picture
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        py-version: ['3.9', '3.10', '3.11']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: ${{ matrix.py-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Run Python
        run: python test.py

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: Picture
          path: picture_${{ matrix.py-version }}.txt
          retention-days: 1

      - name: Send tg message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          document: picture_${{ matrix.py-version }}.txt
